spring.application.name=SkillSwap
server-port = 8080

#database
spring.datasource.url=jdbc:postgresql://194.87.74.42:5432/skillswap
spring.datasource.username=admin
spring.datasource.password=qwerty01965
spring.datasource.driver-class-name=org.postgresql.Driver

#flyway-migration
flyway.enabled=true
flyway.locations=classpath:db/migration
flyway.baseline-on-migrate=true

app.cors.allowed-origins=http://localhost:3000
#app.cors.allowed-origins=http://194.87.74.42:3000

axios.defaults.withCredentials = true;


#multipart-properties
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB