
ALTER TABLE users
ADD COLUMN password VARCHAR(500) NOT NULL,
ADD COLUMN enabled BOOLEAN NOT NULL;

ALTER TABLE users
  ADD CONSTRAINT unique_username UNIQUE (username);

CREATE TABLE authorities (
    username VARCHAR(50) NOT NULL,
     authority  VARCHAR(50) NOT NULL,
  CONSTRAINT FK_AUTHORITIES_USERS FOREIGN KEY (username) REFERENCES users (username)
);

CREATE UNIQUE INDEX IX_AUTH_USERNAME ON AUTHORITIES (username, authority);

